include: "rules/synth.smk"
include: "rules/causalchamber.smk"


fig_2 = expand(
    "results/er_{metric}_ivn={num_intervs}.pdf",
    metric=["ari", "fscore"],
    num_intervs=[2, 5, 8],
)
fig_3 = expand(
    "results/scalability_{compare}.pdf", compare=["ari_samp", "time_samp", "time_nodes"]
)
tab_1 = "results/causalchamber_summary.csv"
fig_4 = "results/causalchamber_dags.txt"
fig_5 = expand(
    "results/sf_{metric}_ivn={num_intervs}.pdf",
    metric=["ari", "fscore"],
    num_intervs=[2, 5, 8],
)


rule all:
    input:
        fig_2,
        tab_1,
        fig_4,
        fig_5,
