from snakemake.io import directory


include: "rules/synth.smk"
include: "rules/causalchamber.smk"


rule all:
    input:
        expand("results/fscores_num_intervs_{num_intervs}.pdf", num_intervs=[2, 5, 8]),
        expand("results/ari_num_intervs_{num_intervs}.pdf", num_intervs=[2, 5, 8]),
        "results/causalchamber/dag.png",
        "results/causalchamber/dag_summary.txt",
        "results/causalchamber/grid_metrics.csv",
        "results/causalchamber/method_metrics.csv",
        "results/causalchamber/ut_grid_metrics.csv",
        "results/causalchamber/grid_runs",
